### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [yferras/javartint#3]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by yferras** [comment]
Hello!!! 
Thanks by your observation. In fact, the actual licence that I'm using is **GPLv3**. But the file *LICENSE.txt* it was inside of the *crow-javartint* directory. Now I moved the licence file to the *root* directory. 

Thanks again.
